import React, { Component } from 'react';
import './landing.css';

export default class Landing extends Component {
  render() {
    return (
      <section className='landing'>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tristique fringilla mi et accumsan. Pellentesque a imperdiet arcu, sit amet elementum sem. Vestibulum vitae eros nisi. Vivamus condimentum tortor eros, id gravida nisi varius vitae. Donec velit nisl, laoreet non tellus vitae, ullamcorper faucibus ex. Mauris eget pharetra sem. Curabitur sapien ligula, vestibulum ut auctor vel, ullamcorper id odio.<br />Suspendisse et lobortis magna. Pellentesque maximus iaculis ultrices. In hendrerit pretium venenatis. Fusce non turpis pellentesque, placerat erat eget, feugiat lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In dui nibh, fermentum ornare dapibus a, ultricies nec dolor. Ut in laoreet velit. Vivamus malesuada turpis nec nisl ultricies, eu volutpat erat dignissim.<br />Nullam egestas, felis quis porta eleifend, eros arcu interdum arcu, id blandit turpis eros sed arcu. Nulla facilisi. Ut non justo velit. Aliquam rhoncus sem ut nulla hendrerit suscipit. Nullam non aliquam dui. Mauris ultrices tristique enim ut bibendum. Ut turpis quam, commodo a eleifend at, imperdiet ut tortor. Suspendisse ligula dui, pharetra quis pulvinar nec, laoreet nec augue.<br />Sed commodo efficitur faucibus. Nullam molestie leo non ante pharetra malesuada. Aenean mauris ligula, tincidunt in pretium eget, consectetur quis augue. Vivamus mollis magna lobortis pulvinar malesuada. Sed ac neque condimentum, egestas turpis in, cursus ante. Donec consectetur vel nunc at fermentum. Cras blandit elementum nisi quis auctor. Duis sed sem nec est imperdiet placerat non aliquam enim. Integer imperdiet odio eu ex sagittis commodo. Etiam sit amet dui iaculis risus lacinia condimentum nec ac nisl.<br />Mauris mauris justo, interdum ac malesuada pulvinar, scelerisque in ligula. Aliquam nulla mauris, vestibulum in fermentum eget, placerat quis quam. Nulla felis nisl, ullamcorper vitae turpis ut, efficitur tempus ligula. Nullam nisi mauris, bibendum vitae risus vel, ullamcorper interdum nisl. Phasellus ultricies sagittis dolor. Mauris sed turpis tristique, convallis velit sed, euismod erat. Curabitur in nulla non erat convallis egestas eget vel nunc. Quisque dapibus mauris velit, sed facilisis augue aliquet vitae. Praesent mollis consequat urna et facilisis. Quisque ut sem euismod, aliquam felis at, facilisis diam. Sed suscipit neque ac elit venenatis ultricies. Donec luctus dui et enim luctus, in elementum ante semper.</p>
      </section>
    )
  }
}